name: dogslife
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.2.4
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  image_picker: ^1.1.2
  flutter_dotenv: ^5.0.2
  provider: ^6.1.5
  package_info_plus: ^4.1.0
  cupertino_icons: ^1.0.8

dependency_overrides:
  win32: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
