final List<Map<String, String>> breedList = [
  {'name': 'Staffordshire Bull Terrier', 'description': 'Popular bull breed, muscular, affectionate, loyal.'},
  {'name': 'American Pit Bull Terrier', 'description': 'Athletic, intelligent, requires experienced handling.'},
  {'name': 'Bull Terrier', 'description': 'Stocky build, egg-shaped head, playful and courageous.'},
  {'name': 'American Bulldog', 'description': 'Large, strong, protective, requires good training.'},
  {'name': 'English Bulldog', 'description': 'Distinctive wrinkled face, gentle, friendly temperament.'},
  {'name': 'French Bulldog', 'description': 'Compact, affectionate, playful, popular companion.'},
  {'name': 'Boxer', 'description': 'Energetic, loyal, excellent family dog with a playful nature.'},
  {'name': 'Rottweiler', 'description': 'Powerful, confident, protective, requires consistent training.'},
  {'name': 'Mastiff', 'description': 'Giant breed, gentle giant, protective, calm demeanour.'},
  {'name': 'Neapolitan Mastiff', 'description': 'Massive size, loose skin, protective and affectionate.'},
  {'name': 'Great Dane', 'description': 'Gentle giant, friendly, excellent with families.'},
  {'name': 'Bullmastiff', 'description': 'Large, loyal, protective, known as quiet guardians.'},
  {'name': 'Mixed Breed (Bull Breed Mix)', 'description': 'Cross of bull breed types, varies in size and temperament.'},
  {'name': 'Labrador Retriever', 'description': 'Friendly, intelligent, excellent family companion.'},
  {'name': 'German Shepherd', 'description': 'Highly intelligent, protective, excellent working dog.'},
  {'name': 'Border Collie', 'description': 'Extremely intelligent, active, excels at agility and herding.'},
  {'name': 'Huntaway', 'description': 'NZ working dog, bred for herding, loyal and energetic.'},
  {'name': 'Kelpie', 'description': 'Australian herding dog, high energy, intelligent and loyal.'},
  {'name': 'Greyhound', 'description': 'Gentle, calm, excellent companions, often retired racers.'},
  {'name': 'Whippet', 'description': 'Small sighthound, fast, friendly, affectionate.'},
  {'name': 'Fox Terrier', 'description': 'Small, energetic, intelligent, excellent vermin hunters.'},
  {'name': 'Jack Russell Terrier', 'description': 'Feisty, energetic, intelligent, requires stimulation.'},
  {'name': 'Shih Tzu', 'description': 'Small, affectionate, low-shedding, good indoor companion.'},
  {'name': 'Maltese', 'description': 'Tiny, affectionate, intelligent, ideal lap dog.'},
  {'name': 'Poodle (Standard/Miniature/Toy)', 'description': 'Intelligent, low-shedding, excellent family companion.'},
  {'name': 'Cavalier King Charles Spaniel', 'description': 'Friendly, affectionate, ideal family companion.'},
  {'name': 'Chihuahua', 'description': 'Tiny, bold, loyal, suited to apartment living.'},
  {'name': 'Spoodle (Cocker Spaniel x Poodle)', 'description': 'Popular designer breed, intelligent, affectionate, low-shedding.'},
  {'name': 'Labradoodle (Labrador x Poodle)', 'description': 'Friendly, intelligent, hypoallergenic potential.'},
  {'name': 'Other (Specify)', 'description': 'Breed not listed, please specify.'},
];
